# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "win7"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.communicator = "winrm"
  config.vm.provision :shell, path: "scripts/InstallChocolatey.ps1"
  config.vm.provision :reload
  config.vm.provision "shell", inline: "choco.exe install google-chrome-x64 -y"
  config.vm.provision "shell", inline: "choco.exe install 7zip -y"
  config.vm.provision "shell", inline: "choco.exe install vim -y"
  config.vm.provision "shell", inline: "choco.exe install git -y"
  # XXX: Consider replacing this version of python with anaconda, since it's
  # hard to install numpy (needs Visual Studio C++) and scipy (requires
  # lapack/blas) with choco's python or the official version at python.org.
  # There are some dll troubles with anaconda, but they seem more tractable
  config.vm.provision "shell", inline: "choco.exe install python -y"
  config.vm.provision "shell", inline: "choco.exe install python2 -y"
  config.vm.provision "shell", inline: "choco.exe install blender -y"
  config.vm.provision "shell", inline: "choco.exe install golang -y"
  config.vm.provision "shell", inline: "choco.exe install mingw -y"
  config.vm.provision "shell", inline: "choco.exe install cygwin -y"
  config.vm.provision :shell, path: "scripts/InstallBabun.ps1"
  config.vm.provision :reload
  config.vm.provision :shell, path: "scripts/MCellTeam.ps1"
  # Windows6.1-KB3050265-x64 need to grab this to speed up windows update
  # Windows6.1-KB2506143-x64 need this for powershell v3
  # Need to run "pact install bison" and "pact install flex" in babun

end
