# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "win7"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.communicator = "winrm"
  config.vm.provision :shell, path: "scripts/InstallChocolatey.ps1"
  config.vm.provision :reload
  config.vm.provision "shell", inline: "choco.exe install google-chrome-x64 -y"
  config.vm.provision "shell", inline: "choco.exe install 7zip -y"
  config.vm.provision "shell", inline: "choco.exe install vim -y"
  config.vm.provision "shell", inline: "choco.exe install git -y"
  config.vm.provision "shell", inline: "choco.exe install python -y"
  config.vm.provision "shell", inline: "choco.exe install python2 -y"
  config.vm.provision "shell", inline: "choco.exe install blender -y"
  config.vm.provision "shell", inline: "choco.exe install golang -y"
  config.vm.provision "shell", inline: "choco.exe install mingw -y"
  config.vm.provision "shell", inline: "choco.exe install cygwin -y"
  config.vm.provision :reload
  config.vm.provision :shell, path: "scripts/MCellTeam.ps1"

end
