# -*- mode: ruby -*-
# vi: set ft=ruby :

# Note: Apple's EULA only allows OSX VMs to be run on Apple hardware.
# The box used in this repo is described here:
# https://github.com/AndrewDryga/vagrant-box-osx
# and here:
# https://atlas.hashicorp.com/AndrewDryga/boxes/vagrant-box-osx/

Vagrant.configure(2) do |config|
  config.vm.box = "http://files.dryga.com/boxes/osx-yosemite-0.2.1.box"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    brew update
  SHELL
end
