# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get remove -y dictionaries-common
    sudo apt-get install -y dictionaries-common
    sudo apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11 zip unzip build-essential autoconf flex bison swig python3-dev default-jdk libglu1-mesa-dev freeglut3-dev mesa-common-dev git python-pip
    # not needed, but i find these to be useful
    sudo apt-get install gnome-terminal exuberant-ctags
  SHELL
end
